### ISSUE TITLE
routes are no longer working after 24 minutes

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentralRouterMacOS#2]
https://github.com/Ylianst/MeshCentralRouter/issues/19

**Comment by Ylianst** [comment]
I don't understand this issue. Is the "not working after 24 minute" for the Windows or macOS version? This is the macOS GitHub repo. I also can't find a reference to this in the link you posted.

**Comment by vtacquet** [comment]
> I don't understand this issue. Is the "not working after 24 minute" for the Windows or macOS version? This is the macOS GitHub repo. I also can't find a reference to this in the link you posted.

It is for the macos version but you fixed it yesterday.
