### ISSUE TITLE
open configuration file does not load mappings, save works

### ISSUE THREAD

**Issue by vtacquet** [Ylianst/MeshCentralRouterMacOS#3]
https://github.com/Ylianst/MeshCentralRouter/issues/19

clicking an .mcrouter file or opening a file via the menu has the same results (I do have lots of groups and devices but I only saved 2 routes)

the .mcrouter file has vaild contents after saving

**Comment by vtacquet** [comment]
there is a comment about the load issue here: https://github.com/Ylianst/MeshCentral/issues/2282#issuecomment-785700555

the password field is also not functional when opening an .mcrouter file

**Comment by Ylianst** [comment]
Ok, I have a fix for this finally. MeshCentral Router v0.0.4 for macOS will be available tomorrow.
